/*
 * AudioWarningTests — Fix-Brief 2 (audio never silently dropped).
 *
 * The contract: when audio is ENABLED and the source HAS a track but the
 * audio can't be produced correctly, the failure is SURFACED (a job
 * warning) while the video still ships — never a silent audio-less /
 * wrong-rate / empty-trak success.
 *
 * The encode flow (A1/A2 in EncodeQueue) needs a malformed-AUDIO source to
 * exercise end-to-end and is covered by the human gate (a valid-container/
 * corrupt-audio MOV can't be fabricated deterministically here). These
 * tests pin the PURE SEAMS the fixes funnel through (mirroring the
 * cropClampSourceDims / previewShouldLoad pattern):
 *   - C: SourceAudioReader.channelsSupported (floor + ceiling).
 *   - D: SourceAudioReader.resolveSampleRate (track-nominal fallback, throw
 *        instead of silent 48k mislabel).
 *   - B: makeS32LEPCMSampleBuffer now THROWS (was: returned nil → empty trak).
 *   - the warning plumbing: EncodeJob.audioWarning field + FrameSink
 *     protocol default.
 */

import XCTest
import CoreMedia
@testable import GlEnc
@testable import GlEncCore

final class AudioWarningTests: XCTestCase {

    // MARK: - C: channel-count floor + ceiling

    func testChannelsSupported_acceptsRealLayouts() {
        XCTAssertTrue(SourceAudioReader.channelsSupported(1))   // mono
        XCTAssertTrue(SourceAudioReader.channelsSupported(2))   // stereo
        XCTAssertTrue(SourceAudioReader.channelsSupported(6))   // 5.1
        XCTAssertTrue(SourceAudioReader.channelsSupported(8))   // 7.1
        XCTAssertTrue(SourceAudioReader.channelsSupported(SourceAudioReader.maxChannels))
    }

    func testChannelsSupported_rejectsPathological() {
        XCTAssertFalse(SourceAudioReader.channelsSupported(0))
        XCTAssertFalse(SourceAudioReader.channelsSupported(-1))
        XCTAssertFalse(SourceAudioReader.channelsSupported(SourceAudioReader.maxChannels + 1))
        XCTAssertFalse(SourceAudioReader.channelsSupported(Int(UInt32.max)))  // 0xFFFFFFFF
    }

    // MARK: - C (integration): the clamp fires end-to-end via readInterleavedPCM

    /// Deterministic integration of the channel-count guard (Fix-Brief 2,
    /// finding C). The pure `channelsSupported` predicate is covered above;
    /// this proves the guard actually fires inside `readInterleavedPCM` when a
    /// real source's ASBD declares > maxChannels — the read path that pulls
    /// `mChannelsPerFrame`, floors at 1, then throws.
    ///
    /// The malformed source is generated by GlEnc's OWN `VariantMOVWriter` —
    /// a bare in32 LPCM trak declaring 100 channels — so it's fully
    /// deterministic: no committed binary, no AVFoundation *decoder*, no AAC
    /// channel limit (AAC can't even carry > 48), no env-dependence. (Step-1
    /// probe verified AVFoundation surfaces `mChannelsPerFrame = 100` from this
    /// trak; third-party multichannel writers refuse it without a layout.)
    func testReadInterleavedPCM_RejectsOver64Channels_Integration() async throws {
        let out = URL(fileURLWithPath: NSTemporaryDirectory())
            .appendingPathComponent("glenc-chanclamp-\(UUID().uuidString).mov")
        defer { try? FileManager.default.removeItem(at: out) }

        let writer = try VariantMOVWriter(
            destURL: out, format: .dxt1, presentationWidth: 64, presentationHeight: 64,
            fps: 30, codecFourCC: "DXD3")
        for _ in 0..<3 {
            try writer.append(packet: Data(repeating: 0xAB, count: 1024), presentationTime: .zero)
        }
        // in32 LPCM audio trak declaring 100 channels — past maxChannels (64).
        let info = AudioStreamInfo(sampleRate: 48000, channels: 100, bitsPerChannel: 32)
        writer.attachAudioTrack(info: info, pcm: Data(count: info.bytesPerFrame * 480))
        try writer.finish()

        do {
            _ = try await SourceAudioReader.readInterleavedPCM(out, targetRate: nil)
            XCTFail("a 100-channel source must throw unsupportedChannelCount, not return audio")
        } catch SourceAudioError.unsupportedChannelCount(let c) {
            XCTAssertEqual(c, 100, "the guard must surface the offending channel count verbatim")
        } catch {
            XCTFail("expected unsupportedChannelCount(100), got \(error)")
        }
    }

    // MARK: - D: rate resolution (track-nominal fallback, throw not silent-48k)

    func testResolveSampleRate_usesPrimaryWhenKnown() throws {
        XCTAssertEqual(try SourceAudioReader.resolveSampleRate(
            primary: 44100, trackNominal: 96000, hasNonEmptyPCM: true), 44100)
    }

    func testResolveSampleRate_fallsBackToTrackNominal() throws {
        // per-sample-buffer ASBD unreadable (primary 0) → use the track rate
        XCTAssertEqual(try SourceAudioReader.resolveSampleRate(
            primary: 0, trackNominal: 96000, hasNonEmptyPCM: true), 96000)
    }

    func testResolveSampleRate_throwsWhenUndeterminableWithData() {
        // real PCM but no rate anywhere → surface, don't mislabel 48k
        XCTAssertThrowsError(try SourceAudioReader.resolveSampleRate(
            primary: 0, trackNominal: 0, hasNonEmptyPCM: true)) { err in
            guard case SourceAudioError.undeterminedSampleRate = err else {
                return XCTFail("expected undeterminedSampleRate, got \(err)")
            }
        }
    }

    func testResolveSampleRate_emptyPCMIsBenign48k() throws {
        // zero-frame track: empty PCM, rate moot (gated out downstream)
        XCTAssertEqual(try SourceAudioReader.resolveSampleRate(
            primary: 0, trackNominal: 0, hasNonEmptyPCM: false), 48000)
    }

    // MARK: - B: makeS32LEPCMSampleBuffer throws (was: silent nil → empty trak)

    func testMakeS32_throwsOnEmptyPCM() {
        let info = AudioStreamInfo(sampleRate: 48000, channels: 2, bitsPerChannel: 32)
        XCTAssertThrowsError(try makeS32LEPCMSampleBuffer(Data(), info: info)) { err in
            guard case FrameSinkError.audioSampleBufferFailed = err else {
                return XCTFail("expected audioSampleBufferFailed, got \(err)")
            }
        }
    }

    func testMakeS32_throwsOnZeroBytesPerFrame() {
        // channels 0 → bytesPerFrame 0 → must throw, not produce a buffer
        let info = AudioStreamInfo(sampleRate: 48000, channels: 0, bitsPerChannel: 32)
        XCTAssertThrowsError(try makeS32LEPCMSampleBuffer(Data([1, 2, 3, 4]), info: info))
    }

    func testMakeS32_succeedsOnValidPCM() throws {
        let info = AudioStreamInfo(sampleRate: 48000, channels: 2, bitsPerChannel: 32)
        // 10 stereo s32 frames = 10 * (2 * 4) = 80 bytes
        let pcm = Data(count: info.bytesPerFrame * 10)
        let sb = try makeS32LEPCMSampleBuffer(pcm, info: info)
        XCTAssertEqual(CMSampleBufferGetNumSamples(sb), 10)
    }

    // MARK: - warning plumbing

    func testEncodeJobAudioWarningDefaultsNilAndIsSettable() {
        var job = EncodeJob(sourceURL: URL(fileURLWithPath: "/tmp/x.mov"))
        XCTAssertNil(job.audioWarning)
        job.audioWarning = "Audio unavailable: test"
        XCTAssertEqual(job.audioWarning, "Audio unavailable: test")
        // distinct from errorMessage (failure-only) and from .done status
        XCTAssertNil(job.errorMessage)
    }

    func testDXVEncoderSinkAudioWarningDefaultsNil() {
        // DXVEncoderSink doesn't write audio via the AVAssetWriter path, so
        // it uses the FrameSink protocol default (nil). (The byte-path audio
        // trak is Brief 3 territory, untouched here.)
        let sink: FrameSink = DXVEncoderSink(
            encoder: DXT1Encoder(),
            writer: NullPacketWriter())
        XCTAssertNil(sink.audioWarning)
    }
}

/// Minimal PacketWriter stub for the DXVEncoderSink protocol-default test
/// (never actually driven — we only read `audioWarning`).
private final class NullPacketWriter: PacketWriter {
    func append(packet: Data, presentationTime: CMTime) throws {}
    func finish() throws {}
}
