// SPDX-License-Identifier: BSD-2-Clause
//
// The LZF decompressor in this file is a hand-port of liblzf
// © Marc Lehmann <schmorp@schmorp.de>, used under the BSD-2-Clause election
// of liblzf's dual BSD-2-Clause / GPLv2 license. (The 4-byte DXV1/DXV2 header
// parser follows FFmpeg's libavcodec/dxv.c; the file as published is
// BSD-2-Clause.) See THIRD-PARTY-NOTICES.md and LICENSES/BSD-2-Clause.txt.
//
// vendored from AmritusG/glance @ e134a3a (v0.7.0), GlEnc's validated pin
//
//  DXV1PacketDecoder.swift
//  GlanceCore
//
//  Read support for the legacy DXV1 / DXV2 packet format (codec FourCC
//  "DXDI"), as a sibling to the DXV3-only path in DXVPacketDecoder.swift.
//
//  Per FFmpeg's libavcodec/dxv.c, the legacy format diverges from DXV3
//  at the packet level:
//    - Header is 4 bytes total, with size+flags+version packed into a
//      single little-endian word (not the DXV3 12-byte tag+version+rawFlag
//      shape).
//    - Payload is either RAW DXT blocks (flag bit 0x80 set) or LZF-
//      compressed DXT blocks (bit clear). No DXV-specific opcode layer.
//    - After decompression, the bytes are raw DXT1 / DXT5 blocks, which
//      feed the same renderer/CGImage path as the existing DXT variants.
//
//  ───────────────────────────────────────────────────────────────────
//  LZF decoder credit:
//
//  The internal `LZF` enum below is a hand-port of the LZF decompressor
//  algorithm published by Marc Lehmann as part of liblzf
//  (http://oldhome.schmorp.de/marc/liblzf.html). liblzf is dual-licensed
//  BSD-2-Clause / GPLv2+; this file uses the BSD-2-Clause terms:
//
//      Copyright (c) 2000-2010 Marc Alexander Lehmann <schmorp@schmorp.de>
//
//      Redistribution and use in source and binary forms, with or without
//      modification, are permitted provided that the following conditions
//      are met:
//
//        1. Redistributions of source code must retain the above copyright
//           notice, this list of conditions and the following disclaimer.
//
//        2. Redistributions in binary form must reproduce the above
//           copyright notice, this list of conditions and the following
//           disclaimer in the documentation and/or other materials provided
//           with the distribution.
//
//      THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS
//      OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
//      WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
//      ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
//      DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
//      DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
//      GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
//      INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
//      WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
//      NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//      SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
//  Only the decompressor is ported (encoder is not needed — Glance is a
//  read-only player). Validated against fixtures generated by the
//  upstream `python-lzf` binding to the same C library.
//

import Foundation

/// Parser + decompressor for legacy DXV1 / DXV2 ("DXDI") video packets.
///
/// Each packet starts with a single little-endian 4-byte tag word:
///
///     bits 0..23   payload size (bytes following the 4-byte tag)
///     bits 24..27  version_major + 1  (DXV1 = 1, DXV2 = 2)
///     bits 28..31  flag nibble:
///       bit 0x20 → texture is DXT1 (also implied by version_major==1)
///       bit 0x40 → texture is DXT5
///       bit 0x80 → payload is RAW (uncompressed). Bit clear → LZF.
///
/// After header strip, the payload (RAW or LZF-decompressed) is a flat
/// stream of DXT1 or DXT5 blocks suitable for `glCompressedTexImage2D` —
/// the same shape `DXVPacketDecoder.decompressDXT1/DXT5` produces for
/// the DXV3 path.
public enum DXV1PacketDecoder {

    public enum DecodeError: Error, CustomStringConvertible {
        case packetTooSmall(size: Int)
        case unsupportedTexture(flags: UInt8, version: UInt8)
        case payloadTruncated(declared: Int, available: Int)
        case lzfFailed(message: String)
        public var description: String {
            switch self {
            case .packetTooSmall(let s):
                return "Packet too small: \(s) bytes (need 4+ for legacy header)"
            case .unsupportedTexture(let f, let v):
                return String(format: "Unsupported legacy DXV texture: flags=0x%02X version=%d",
                              f, v)
            case .payloadTruncated(let d, let a):
                return "Legacy DXV payload truncated: declared=\(d), available=\(a)"
            case .lzfFailed(let m):
                return "LZF decompression failed: \(m)"
            }
        }
    }

    /// Resolved texture format carried by a legacy DXV packet.
    public enum TextureFormat {
        case dxt1
        case dxt5
    }

    /// Parsed legacy DXV packet header.
    public struct PacketHeader {
        /// Bits 0..23 of the 32-bit tag — the payload byte count.
        public let payloadSize: UInt32
        /// Bits 28..31 of the 32-bit tag, i.e. `old_type & 0xF0`.
        public let flagsNibble: UInt8
        /// `version_major = (old_type & 0x0F) - 1`. Per FFmpeg dxv.c
        /// the encoder writes `version + 1` into the low nibble of
        /// `old_type`, so DXV1 stores `0x01`, DXV2 stores `0x02`.
        public let versionMajor: UInt8
        /// Resolved texture format from the flag nibble.
        public let textureFormat: TextureFormat
        /// True when bit 0x80 is set — payload is uncompressed.
        public let isRaw: Bool

        public init(payloadSize: UInt32,
                    flagsNibble: UInt8,
                    versionMajor: UInt8,
                    textureFormat: TextureFormat,
                    isRaw: Bool) {
            self.payloadSize = payloadSize
            self.flagsNibble = flagsNibble
            self.versionMajor = versionMajor
            self.textureFormat = textureFormat
            self.isRaw = isRaw
        }
    }

    /// Read the 4-byte legacy header out of `packet` and slice off the
    /// payload. Mirrors `DXVPacketDecoder.parseHeader` in shape so call
    /// sites can dispatch by generation and use whichever decoder fits.
    ///
    /// `packet` should be the full DXV1 chunk (4-byte header + payload),
    /// as the demuxer's `stsz`/`stco`-derived `DXVFrameEntry` reports it.
    public static func parseHeader(_ packet: Data) throws -> (header: PacketHeader, payload: Data) {
        let header = try decodeTagWord(packet)
        let payloadEnd = 4 + Int(header.payloadSize)
        let availablePayload = packet.count - 4
        guard payloadEnd <= packet.count else {
            throw DecodeError.payloadTruncated(declared: Int(header.payloadSize),
                                               available: availablePayload)
        }
        let base = packet.startIndex
        let payload = packet.subdata(in: (base + 4)..<(base + payloadEnd))
        return (header, payload)
    }

    /// Decode only the 4-byte tag word, without requiring the payload
    /// bytes to follow in `tagWord`. Used by the demuxer's variant-peek
    /// path where we need to read the texture-format flags from the
    /// first packet's head without slurping the whole packet off disk.
    internal static func parseTagWord(_ tagWord: Data) throws -> PacketHeader {
        return try decodeTagWord(tagWord)
    }

    private static func decodeTagWord(_ d: Data) throws -> PacketHeader {
        guard d.count >= 4 else {
            throw DecodeError.packetTooSmall(size: d.count)
        }
        let base = d.startIndex
        let tag = UInt32(d[base])
            | (UInt32(d[base + 1]) << 8)
            | (UInt32(d[base + 2]) << 16)
            | (UInt32(d[base + 3]) << 24)

        // The nibble-decode below mirrors FFmpeg's libavcodec/dxv.c default
        // (legacy DXDI) case in dxv_decode(), reproduced verbatim from
        // https://raw.githubusercontent.com/FFmpeg/FFmpeg/master/libavcodec/dxv.c
        // (master, 2026-05-19):
        //
        //   464: size = tag & 0x00FFFFFF;
        //   465: old_type = tag >> 24;
        //   466: version_major = (old_type & 0x0F) - 1;
        //   467:
        //   468: if (old_type & 0x80) {
        //   469:     msgcomp = "RAW";
        //   470:     decompress_tex = dxv_decompress_raw;
        //   471: } else {
        //   472:     msgcomp = "LZF";
        //   473:     decompress_tex = dxv_decompress_lzf;
        //   474: }
        //   475:
        //   476: if (old_type & 0x40) {
        //   477:     tag = DXV_FMT_DXT5;
        //   478:     msgtext = "DXT5";
        //   ...
        //   483: } else if (old_type & 0x20 || version_major == 1) {
        //   484:     tag = DXV_FMT_DXT1;
        //   485:     msgtext = "DXT1";
        //   ...
        //   490: } else {
        //   491:     av_log(avctx, AV_LOG_ERROR, "Unsupported header ...");
        //   492:     return AVERROR_INVALIDDATA;
        //   493: }
        //
        // Notes on the off-by-one numbering: FFmpeg stores `version_major + 1`
        // in the low nibble, so the user-facing "DXV2" maps to nibble value 2
        // → `version_major == 1` in the source. The implicit DXT1 fallback
        // (no 0x20/0x40 flag) only fires when `version_major == 1` (i.e. a
        // DXV2-tagged file with neither texture flag set).
        let payloadSize = tag & 0x00FF_FFFF
        let oldType = UInt8((tag >> 24) & 0xFF)
        let flagsNibble = oldType & 0xF0
        let versionMajor = (oldType & 0x0F) &- 1
        let isRaw = (oldType & 0x80) != 0

        let format: TextureFormat
        if (oldType & 0x40) != 0 {
            format = .dxt5
        } else if (oldType & 0x20) != 0 || versionMajor == 1 {
            format = .dxt1
        } else {
            throw DecodeError.unsupportedTexture(flags: flagsNibble, version: versionMajor)
        }

        return PacketHeader(payloadSize: payloadSize,
                            flagsNibble: flagsNibble,
                            versionMajor: versionMajor,
                            textureFormat: format,
                            isRaw: isRaw)
    }

    /// Decode the packet payload into raw DXT block bytes. For RAW
    /// packets this is a `prefix(expectedSize)` slice; for LZF packets
    /// the payload is decompressed.
    public static func decodePayload(_ payload: Data,
                                     header: PacketHeader,
                                     expectedSize: Int) throws -> Data {
        if header.isRaw {
            guard payload.count >= expectedSize else {
                throw DecodeError.payloadTruncated(declared: expectedSize,
                                                   available: payload.count)
            }
            return payload.prefix(expectedSize)
        }
        do {
            return try LZF.decompress(payload, expectedSize: expectedSize)
        } catch let e as LZF.LZFError {
            throw DecodeError.lzfFailed(message: e.description)
        }
    }

    // MARK: - LZF (Marc Lehmann's algorithm, BSD-2-Clause)

    /// Pure-Swift hand-port of liblzf's `lzf_decompress`. Decompressor
    /// only. The LZF stream is a sequence of opcodes:
    ///
    ///   ctrl < 32   literal run of (ctrl + 1) bytes follow
    ///   ctrl >= 32  back-reference
    ///       top 3 bits = length (1..7), or extended if 7
    ///       low 5 bits + next byte = 13-bit offset
    ///       reference position = output_pos - offset - 1
    ///       copy length+2 bytes from reference forward
    ///
    /// Self-overlapping copies (offset < length) are required — they
    /// behave like run-length encoding, which is how all-zeros or
    /// repeated-pattern streams compress so densely.
    ///
    /// `internal` (not public) because DXV1 is the only consumer in this
    /// codebase. The unit tests reach it via `@testable import GlanceCore`.
    internal enum LZF {
        internal enum LZFError: Error, CustomStringConvertible {
            case truncatedInput(needed: Int, atOffset: Int)
            case outputOverflow(produced: Int, expected: Int)
            case backRefOutOfRange(offset: Int, atOutputPos: Int)
            public var description: String {
                switch self {
                case .truncatedInput(let n, let o):
                    return "LZF input truncated: needed \(n) more byte(s) at input offset \(o)"
                case .outputOverflow(let p, let e):
                    return "LZF output overflow: produced \(p), expected \(e)"
                case .backRefOutOfRange(let off, let pos):
                    return "LZF back-reference offset \(off) > output pos \(pos)"
                }
            }
        }

        /// Decompress an LZF-compressed input into a buffer of exactly
        /// `expectedSize` bytes. Throws if the stream is malformed, the
        /// output overflows or underflows, or a back-reference points
        /// before the start of the output.
        internal static func decompress(_ input: Data, expectedSize: Int) throws -> Data {
            if expectedSize == 0 {
                if input.isEmpty {
                    return Data()
                }
                throw LZFError.outputOverflow(produced: input.count, expected: 0)
            }
            var output = Data(count: expectedSize)
            let produced: Int = try output.withUnsafeMutableBytes { outRaw in
                guard let outBase = outRaw.baseAddress?.assumingMemoryBound(to: UInt8.self) else {
                    return 0
                }
                return try input.withUnsafeBytes { inRaw in
                    guard let inBase = inRaw.baseAddress?.assumingMemoryBound(to: UInt8.self) else {
                        return 0
                    }
                    return try decompressInner(
                        input: inBase, inputSize: input.count,
                        output: outBase, outputCapacity: expectedSize)
                }
            }
            if produced != expectedSize {
                throw LZFError.outputOverflow(produced: produced, expected: expectedSize)
            }
            return output
        }

        private static func decompressInner(
            input: UnsafePointer<UInt8>, inputSize: Int,
            output: UnsafeMutablePointer<UInt8>, outputCapacity: Int
        ) throws -> Int {
            var ip = 0
            var op = 0

            while ip < inputSize {
                let ctrl = Int(input[ip]); ip += 1

                if ctrl < 32 {
                    let runLen = ctrl + 1
                    guard ip + runLen <= inputSize else {
                        throw LZFError.truncatedInput(needed: runLen - (inputSize - ip),
                                                     atOffset: ip)
                    }
                    guard op + runLen <= outputCapacity else {
                        throw LZFError.outputOverflow(produced: op + runLen,
                                                     expected: outputCapacity)
                    }
                    for _ in 0..<runLen {
                        output[op] = input[ip]
                        op += 1
                        ip += 1
                    }
                } else {
                    var length = ctrl >> 5
                    if length == 7 {
                        guard ip < inputSize else {
                            throw LZFError.truncatedInput(needed: 1, atOffset: ip)
                        }
                        length += Int(input[ip]); ip += 1
                    }
                    length += 2

                    guard ip < inputSize else {
                        throw LZFError.truncatedInput(needed: 1, atOffset: ip)
                    }
                    let offsetLow = Int(input[ip]); ip += 1
                    let offset = ((ctrl & 0x1F) << 8) | offsetLow
                    let refBack = offset + 1

                    guard refBack <= op else {
                        throw LZFError.backRefOutOfRange(offset: refBack, atOutputPos: op)
                    }
                    guard op + length <= outputCapacity else {
                        throw LZFError.outputOverflow(produced: op + length,
                                                     expected: outputCapacity)
                    }
                    let refStart = op - refBack
                    for k in 0..<length {
                        output[op + k] = output[refStart + k]
                    }
                    op += length
                }
            }
            return op
        }
    }
}
